name: ci

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-lib:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.16.0
          registry-url: https://npm.pkg.github.com/

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@8 --activate

      - name: Set github repository
        run: pnpm config set //https://npm.pkg.github.com//:_authToken ${{secrets.GITHUB_TOKEN}}

      - name: Install dependencies
        run: pnpm install

      - name: Build lib
        run: pnpm run build
        
      - name: Test lib
        run: pnpm run test
